#!/bin/bash
# Quick Start - Admin Authentication Setup

echo "=========================================="
echo "UniFee Admin Authentication Setup"
echo "=========================================="
echo ""
echo "✅ STEP 1: Create Admin User in Supabase"
echo "   1. Go to: Supabase Dashboard > Authentication > Users"
echo "   2. Click 'Add user'"
echo "   3. Email: admin@unifee.com"
echo "   4. Password: Admin@123456"
echo "   5. Click 'Create user'"
echo ""
echo "✅ STEP 2: Copy Admin User ID"
echo "   1. Find admin@unifee.com in the users list"
echo "   2. Click the email to view details"
echo "   3. Copy the User ID (UUID format)"
echo ""
echo "✅ STEP 3: Create Staff Profile Record"
echo "   1. Go to: Supabase Dashboard > SQL Editor"
echo "   2. Run this SQL query (paste actual UUID):"
echo ""
echo "   INSERT INTO public.staff_profiles (id, role, department)"
echo "   VALUES ('PASTE_ADMIN_USER_ID_HERE', 'Admin', 'Administration')"
echo "   ON CONFLICT (id) DO NOTHING;"
echo ""
echo "=========================================="
echo "TESTING THE FIX"
echo "=========================================="
echo ""
echo "1. Start dev server: npm run dev"
echo "2. Open: http://localhost:3000"
echo "3. Click: Sign In"
echo "4. Enter:"
echo "   Email: admin@unifee.com"
echo "   Password: Admin@123456"
echo "5. Expected: Redirected to /admin/dashboard ✅"
echo ""
echo "If redirected to student dashboard instead:"
echo "   - Check browser console (F12) for errors"
echo "   - Verify staff_profiles record exists"
echo "   - Try clearing cookies and logging in again"
echo "   - Run: node scripts/verify-admin-setup.mjs"
echo ""
echo "=========================================="
echo "USEFUL COMMANDS"
echo "=========================================="
echo ""
echo "npm run dev              - Start development server"
echo "npm run build            - Build for production"
echo "npm run start            - Start production server"
echo ""
echo "node scripts/verify-admin-setup.mjs  - Verify admin setup"
echo ""
echo "=========================================="
